# project:
#   type: website
# 
# website:
#   title: "What the Dickens!"
#   navbar:
#     right:
#       - about.qmd
#       - icon: github
#         href: https://github.com/
#       - icon: twitter
#         href: https://twitter.com
# format:
#   html:
#     theme:
#       - cosmo
#       - brand
#     css: styles.css

project:
  type: book

book:
  title: "What the Dickens"
  author: "Des Ryan"
  chapters:
    - index.qmd
    # - posts/beautiful_ireland/index.qmd
    - posts/opening_ceremony/index.qmd
    - posts/history_of_leather_industry/index.qmd
    - posts/kennedy_o_brien/index.qmd
    - posts/reginald_dickens/notes.qmd
    - posts/shareholders/index.qmd
editor: visual

publish:
  gh-pages: true
